# LiteLLM Proxy 配置文件
# 支援多個LLM提供商的統一API代理

model_list:
  # OpenAI 模型
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
      rpm: 60  # 每分鐘請求限制
  
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
      rpm: 60

  # Anthropic 模型
  - model_name: claude-3-haiku
    litellm_params:
      model: anthropic/claude-3-haiku-20240307
      api_key: os.environ/ANTHROPIC_API_KEY
      rpm: 60
  
  - model_name: claude-3-sonnet
    litellm_params:
      model: anthropic/claude-3-sonnet-20240229
      api_key: os.environ/ANTHROPIC_API_KEY
      rpm: 60

  # DeepSeek 模型
  - model_name: deepseek-chat
    litellm_params:
      model: deepseek/deepseek-chat
      api_key: os.environ/DEEPSEEK_API_KEY
      api_base: https://api.deepseek.com
      rpm: 60
  
  - model_name: deepseek-coder
    litellm_params:
      model: deepseek/deepseek-coder
      api_key: os.environ/DEEPSEEK_API_KEY
      api_base: https://api.deepseek.com
      rpm: 60

  # Google AI 模型 (如果有API密鑰)
  - model_name: gemini-pro
    litellm_params:
      model: google/gemini-pro
      api_key: os.environ/GOOGLE_API_KEY
      rpm: 60

# 路由設置
router_settings:
  routing_strategy: simple-shuffle  # 簡單隨機路由
  model_group_alias:  # 模型組別名
    gpt-4: ["gpt-4o"]
    claude: ["claude-3-haiku", "claude-3-sonnet"]
    deepseek: ["deepseek-chat", "deepseek-coder"]
    gemini: ["gemini-pro"]

# 通用設置
general_settings:
  completion_model: claude-3-haiku  # 默認模型
  max_budget: 100  # 最大預算 (USD)
  budget_duration: 30d  # 預算週期

# 日誌設置
litellm_settings:
  drop_params: true  # 丟棄不支援的參數
  set_verbose: false  # 詳細日誌
  json_logs: true    # JSON格式日誌
  
# 安全設置
security_settings:
  master_key: sk-litellm-master-key  # 主密鑰
  ui_access_mode: admin_only         # UI訪問模式
  
# 健康檢查
health_check:
  enabled: true
  interval: 30  # 秒