# Railway deployment configuration for JobSpy Flask application
# Optimized for Railway's Python environment

[variables]
# Environment variables
FLASK_ENV = "production"
FLASK_DEBUG = "false"
PYTHON_VERSION = "3.10"

[phases.setup]
# System dependencies
cmds = [
    "apt-get update",
    "apt-get install -y build-essential curl git"
]

[phases.install]
# Install Python dependencies
cmds = [
    "pip3 install --upgrade pip setuptools wheel",
    "pip3 install -e .",
    "pip3 install -r web_app/requirements.txt"
]

[phases.build]
# Build phase
cmds = [
    "echo 'JobSpy build completed successfully'"
]

[start]
# Start command for production
cmd = "cd web_app && python3 -m gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --access-logfile - --error-logfile -"
