# Railway 配置文件
# 這個文件告訴 Railway 如何構建和部署你的 Flask 應用

[build]
# 構建指令
builder = "nixpacks"

[deploy]
# 部署設定
startCommand = "cd web_app && gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"

[environments.production]
# 生產環境變數
variables = { FLASK_ENV = "production", FLASK_DEBUG = "false" }
