# Railway configuration for JobSpy deployment
# Optimized for Python Flask application

[build]
# Build configuration
builder = "nixpacks"

[deploy]
# Deployment settings
startCommand = "cd web_app && python3 -m gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --access-logfile - --error-logfile -"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
# Production environment variables
variables = { FLASK_ENV = "production", FLASK_DEBUG = "false", PYTHONPATH = "/app" }
